print("Welcome the tip Calculator.")
bill = input("What was the total bill?  $")
tip = input("What percentage tip would you like to give? 10, 12, or 15?")
people = input("How many people to split the bill?")
each = float( (int(float(bill)) * (1 + (float(tip)/100)) ) / int(people) )
each = round(each, 2)
print(f"Each person should pay: ${each}")
